service: aws-nodejs

provider:
  name: aws
  runtime: nodejs4.3
  stage: beta
  region: us-west-2

package:
  include:
    - .env

functions:
  receive:
    handler: handler.receive
    memorySize: 256
    events:
      - http: POST receive
